name: Publish NuGet Packages

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      shell: bash
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Test
      run: dotnet test --verbosity normal
      
    - name: Pack WPFNode.Abstracts
      run: dotnet pack WPFNode.Abstracts\WPFNode.Abstracts.csproj --configuration Release --no-build --output ${{ github.workspace }}\nupkgs /p:Version=${{ env.VERSION }}
    
    - name: Pack WPFNode.Models
      run: dotnet pack WPFNode.Models\WPFNode.Models.csproj --configuration Release --no-build --output ${{ github.workspace }}\nupkgs /p:Version=${{ env.VERSION }}
      
    - name: Pack WPFNode.ViewModels
      run: dotnet pack WPFNode.ViewModels\WPFNode.ViewModels.csproj --configuration Release --no-build --output ${{ github.workspace }}\nupkgs /p:Version=${{ env.VERSION }}
    
    - name: Pack WPFNode
      run: dotnet pack WPFNode\WPFNode.csproj --configuration Release --no-build --output ${{ github.workspace }}\nupkgs /p:Version=${{ env.VERSION }}
      
    - name: Pack WPFNode.Plugins.Basic
      run: dotnet pack WPFNode.Plugins.Basic\WPFNode.Plugins.Basic.csproj --configuration Release --no-build --output ${{ github.workspace }}\nupkgs /p:Version=${{ env.VERSION }}
      
    - name: Push to NuGet
      run: |
        dotnet nuget push "${{ github.workspace }}\nupkgs\dev.breadpack.WPFNode.Abstracts.*.nupkg" --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate
        dotnet nuget push "${{ github.workspace }}\nupkgs\dev.breadpack.WPFNode.Models.*.nupkg" --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate
        dotnet nuget push "${{ github.workspace }}\nupkgs\dev.breadpack.WPFNode.ViewModels.*.nupkg" --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate
        dotnet nuget push "${{ github.workspace }}\nupkgs\dev.breadpack.WPFNode.*.nupkg" --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate
        dotnet nuget push "${{ github.workspace }}\nupkgs\dev.breadpack.WPFNode.Plugins.Basic.*.nupkg" --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate
